### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by wuxiaoxue1006** [ronjonxu/NAID#1]
I was wondering if the pictures you took in your experiment were all under natural lighting conditions? How to get the Huawei camera used, I want to use it to take some data.

**Comment by ronjonxu** [comment]
Thank you for your interest in our work. First, all ground truths are taken at night with additional light, corresponding noisy images are taken without the extra illumination. Second, as for the Huawei camera X2381-VG, it is a surveillance camera that can provide additional IR light. It can be controlled via the internet control. In this way, we can change camera parameters conveniently and keeping the camera still.

**Comment by ronjonxu** [comment]
Thank you for your interest in our work. First, all ground truths are taken at night with additional light, corresponding noisy images are taken without the extra illumination. Second, as for the Huawei camera X2381-VG, it is a surveillance camera that can provide additional IR light. It can be controlled via the internet control. In this way, we can change camera parameters conveniently and keeping the camera still.
