### ISSUE TITLE
image missing of proposed dataset

### ISSUE THREAD

**Issue by kaiq663** [ronjonxu/NAID#2]
There seems to be a lack of  a .DS_gt.png, what is it? The log is as follows.

[ WARN:0@87.413] global loadsave.cpp:248 findDecoder imread_('/dataset/home/noise/Real-NAID/train/gt/.DS_gt.png'): can't open/read file: check file path/integrity
[ WARN:0@88.414] global loadsave.cpp:248 findDecoder imread_('/dataset/home/noise/Real-NAID/train/gt/.DS_gt.png'): can't open/read file: check file path/integrity
[ WARN:0@89.416] global loadsave.cpp:248 findDecoder imread_('/dataset/home/noise/Real-NAID/train/gt/.DS_gt.png'): can't open/read file: check file path/integrity
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 211/211 [01:30<00:00,  2.34it/s]
('/dataset/home/noise/Real-NAID/train/gt/.DS_gt.png', 1) OSError
('/dataset/home/noise/Real-NAID/train/gt/.DS_gt.png', 1) OSError
('/dataset/home/noise/Real-NAID/train/gt/.DS_gt.png', 1) OSError

**Comment by ronjonxu** [comment]
It doesn't belong to our dataset and I have changed the code to omit it.
